name: Predict Using GPT-4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Use the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest version
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Use requirements.txt if you have one
        # Or install dependencies directly
        pip install openai requests

    - name: List files in directory
      run: ls -la

    - name: Run prediction script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python predict_model.py
